export interface Resource {
  title: string;
  url: string;
  description?: string;
}

export interface Section {
  id: string;
  title: string;
  description?: string;
  resources: Resource[];
}

export const sections: Section[] = [
  {
    id: "useful-links",
    title: "Useful Links",
    resources: [
      { title: "Cloud Build product page", url: "https://cloud.google.com/build" },
      { title: "Cloud Build documentation", url: "https://cloud.google.com/build/docs" },
      { title: "Cloud Build release notes", url: "https://cloud.google.com/build/docs/release-notes" },
      { title: "Build configuration file schema", url: "https://cloud.google.com/build/docs/build-config-file-schema" },
      { title: "Cloud Build pricing", url: "https://cloud.google.com/build/pricing" },
      { title: "Cloud Build quotas and limits", url: "https://cloud.google.com/build/quotas" },
      { title: "Cloud Build locations", url: "https://cloud.google.com/build/docs/locations" },
      { title: "Cloud Build console", url: "https://console.cloud.google.com/cloud-build" },
      { title: "CI/CD on Google Cloud", url: "https://cloud.google.com/docs/ci-cd" },
      { title: "Artifact Registry documentation", url: "https://cloud.google.com/artifact-registry/docs" },
      { title: "Cloud Deploy documentation", url: "https://cloud.google.com/deploy/docs" },
      { title: "Cloud Build public issue tracker", url: "https://issuetracker.google.com/issues?q=componentid:190802" },
      { title: "Official builder catalog", url: "https://github.com/GoogleCloudPlatform/cloud-builders" },
      { title: "Community builder catalog", url: "https://github.com/GoogleCloudPlatform/cloud-builders-community" },
      { title: "Cloud Build samples", url: "https://github.com/GoogleCloudPlatform/cloud-build-samples" },
      { title: "Cloud Build notifiers", url: "https://github.com/GoogleCloudPlatform/cloud-build-notifiers" },
      { title: "Google Cloud buildpacks", url: "https://github.com/GoogleCloudPlatform/buildpacks" },
      { title: "Stack Overflow: google-cloud-build", url: "https://stackoverflow.com/questions/tagged/google-cloud-build" },
    ],
  },
  {
    id: "whats-new",
    title: "What's New Since 2021",
    resources: [
      { title: "2021: Private pools GA", url: "https://cloud.google.com/build/docs/private-pools/private-pools-overview", description: "VPC-connected, enterprise-isolated builds became a first-class option." },
      { title: "2022: Regional builds and triggers GA", url: "https://cloud.google.com/build/docs/locations", description: "Data residency, latency, and private networking improvements." },
      { title: "2022: Software Delivery Shield", url: "https://cloud.google.com/software-delivery-shield/docs/overview", description: "Connects Cloud Build, Artifact Registry, Binary Authorization, and provenance into one supply chain story." },
      { title: "2023: Cloud Build repositories (2nd gen)", url: "https://cloud.google.com/build/docs/repositories", description: "Modernized repository connections for GitHub, GitLab, and Bitbucket." },
      { title: "2023: SLSA v1.0 build provenance", url: "https://cloud.google.com/build/docs/securing-builds/generate-validate-build-provenance", description: "Google-signed OIDC identity tokens for secure downstream integrations." },
      { title: "2024: Bitbucket Cloud & Data Center support", url: "https://cloud.google.com/build/docs/automating-builds/bitbucket/build-repos-from-bitbucket-cloud", description: "2nd gen source integrations for Bitbucket." },
      { title: "2024: Default service account changes", url: "https://cloud.google.com/build/docs/cloud-build-service-account-updates", description: "Explicit user-managed service accounts are now the safer default." },
      { title: "2025: Developer Connect triggers GA", url: "https://cloud.google.com/developer-connect/docs/overview", description: "Preferred route for several source providers." },
      { title: "2025: Expanded private pool machine families", url: "https://cloud.google.com/build/docs/private-pools/create-manage-private-pools", description: "c3 and n2d machine families for higher-performance builds." },
    ],
  },
  {
    id: "quickstarts",
    title: "Quickstarts",
    resources: [
      { title: "Build and push a Docker image", url: "https://cloud.google.com/build/docs/build-push-docker-image" },
      { title: "Build Go applications", url: "https://cloud.google.com/build/docs/building/build-go" },
      { title: "Build Java applications", url: "https://cloud.google.com/build/docs/building/build-java" },
      { title: "Build Node.js applications", url: "https://cloud.google.com/build/docs/building/build-nodejs" },
      { title: "Build applications with buildpacks", url: "https://cloud.google.com/docs/buildpacks/build-application" },
      { title: "Deploy to Cloud Run with Cloud Build", url: "https://cloud.google.com/build/docs/deploying-builds/deploy-cloud-run" },
      { title: "Create and manage build triggers", url: "https://cloud.google.com/build/docs/triggers" },
      { title: "Store artifacts in Artifact Registry", url: "https://cloud.google.com/build/docs/building/store-artifacts-in-artifact-registry" },
      { title: "Create your first Cloud Deploy pipeline", url: "https://cloud.google.com/deploy/docs/deploy-app-run" },
    ],
  },
  {
    id: "tutorials",
    title: "Tutorials",
    resources: [
      { title: "GitOps-style continuous delivery with Cloud Build and GKE", url: "https://cloud.google.com/kubernetes-engine/docs/tutorials/gitops-cloud-build" },
      { title: "Access private GitHub repositories from builds", url: "https://cloud.google.com/build/docs/access-github-from-build" },
      { title: "Run builds from GitHub", url: "https://cloud.google.com/build/docs/automating-builds/github/build-repos-from-github" },
      { title: "Use private pools in a private network", url: "https://cloud.google.com/build/docs/private-pools/use-in-private-network" },
      { title: "Access private GKE clusters from private pools", url: "https://cloud.google.com/build/docs/private-pools/access-private-gke-clusters-with-cloud-build-private-pools" },
      { title: "Configure third-party notifications", url: "https://cloud.google.com/build/docs/configuring-notifications/configure-third-party-notifications" },
      { title: "Generate and validate build provenance", url: "https://cloud.google.com/build/docs/securing-builds/generate-validate-build-provenance" },
      { title: "View security insights for builds", url: "https://cloud.google.com/build/docs/securing-builds/view-build-security-insights" },
      { title: "Manage build dependencies", url: "https://cloud.google.com/build/docs/building/manage-dependencies" },
      { title: "Speed up builds", url: "https://cloud.google.com/build/docs/optimize-builds/speeding-up-builds" },
      { title: "Best practices for speeding up builds", url: "https://cloud.google.com/build/docs/optimize-builds/best-practices" },
      { title: "Deploy to Cloud Run using Cloud Deploy", url: "https://cloud.google.com/deploy/docs/deploy-app-run" },
      { title: "Deploy to GKE using Cloud Deploy", url: "https://cloud.google.com/deploy/docs/gke-deploy-app" },
      { title: "Build and deploy on GitHub with Workload Identity Federation", url: "https://github.com/google-github-actions/auth" },
    ],
  },
  {
    id: "security",
    title: "Security & Supply Chain",
    resources: [
      { title: "Secure your builds overview", url: "https://cloud.google.com/build/docs/securing-builds/secure-builds-overview" },
      { title: "Generate and validate SLSA build provenance", url: "https://cloud.google.com/build/docs/securing-builds/generate-validate-build-provenance" },
      { title: "Use Google-signed OIDC tokens", url: "https://cloud.google.com/build/docs/securing-builds/oidc" },
      { title: "View build security insights", url: "https://cloud.google.com/build/docs/securing-builds/view-build-security-insights" },
      { title: "Use user-specified service accounts", url: "https://cloud.google.com/build/docs/securing-builds/configure-user-specified-service-accounts" },
      { title: "Configure private pools", url: "https://cloud.google.com/build/docs/private-pools/private-pools-overview" },
      { title: "Software Delivery Shield overview", url: "https://cloud.google.com/software-delivery-shield/docs/overview" },
      { title: "Artifact Analysis and SBOM guidance", url: "https://cloud.google.com/artifact-analysis/docs" },
      { title: "Binary Authorization documentation", url: "https://cloud.google.com/binary-authorization/docs" },
      { title: "SLSA verifier", url: "https://github.com/slsa-framework/slsa-verifier" },
    ],
  },
  {
    id: "repositories",
    title: "Repositories, Triggers & Source Integrations",
    description: "Cloud Build supports repository, webhook, Pub/Sub, and manual triggers. For broader event-driven automation, teams pair Cloud Build with Eventarc, Workflows, or Cloud Run.",
    resources: [
      { title: "Cloud Build repositories overview", url: "https://cloud.google.com/build/docs/repositories" },
      { title: "Developer Connect overview", url: "https://cloud.google.com/developer-connect/docs/overview" },
      { title: "Create and manage triggers", url: "https://cloud.google.com/build/docs/triggers" },
      { title: "Build from GitHub", url: "https://cloud.google.com/build/docs/automating-builds/github/build-repos-from-github" },
      { title: "Build from GitHub Enterprise", url: "https://cloud.google.com/build/docs/automating-builds/github/build-repos-from-github-enterprise" },
      { title: "Build from GitLab", url: "https://cloud.google.com/build/docs/automating-builds/gitlab/build-repos-from-gitlab" },
      { title: "Build from GitLab Enterprise", url: "https://cloud.google.com/build/docs/automating-builds/gitlab/build-repos-from-gitlab-enterprise-edition" },
      { title: "Build from Bitbucket Cloud", url: "https://cloud.google.com/build/docs/automating-builds/bitbucket/build-repos-from-bitbucket-cloud" },
      { title: "Build from Bitbucket Data Center", url: "https://cloud.google.com/build/docs/automating-builds/bitbucket/build-repos-from-bitbucket-data-center" },
      { title: "Webhook triggers", url: "https://cloud.google.com/build/docs/automating-builds/create-webhook-triggers" },
      { title: "Pub/Sub triggers", url: "https://cloud.google.com/build/docs/automate-builds-pubsub-events" },
      { title: "Manual triggers", url: "https://cloud.google.com/build/docs/manually-build-code-source-repos" },
    ],
  },
  {
    id: "private-pools",
    title: "Private Pools & Regional Builds",
    resources: [
      { title: "Private pools overview", url: "https://cloud.google.com/build/docs/private-pools/private-pools-overview" },
      { title: "Create and manage private pools", url: "https://cloud.google.com/build/docs/private-pools/create-manage-private-pools" },
      { title: "Use private pools in a private network", url: "https://cloud.google.com/build/docs/private-pools/use-in-private-network" },
      { title: "Access private GKE clusters with private pools", url: "https://cloud.google.com/build/docs/private-pools/access-private-gke-clusters-with-cloud-build-private-pools" },
      { title: "Cloud Build locations", url: "https://cloud.google.com/build/docs/locations" },
      { title: "Cloud Build pricing", url: "https://cloud.google.com/build/pricing" },
      { title: "Choose machine types and CPU scaling options", url: "https://cloud.google.com/build/docs/optimize-builds/increase-vcpu-for-builds" },
    ],
  },
  {
    id: "cloud-deploy",
    title: "Cloud Deploy & Delivery",
    description: "Cloud Build is excellent for CI and simple build-then-deploy flows. For staged promotions, approvals, and environment-specific release controls, use Cloud Build for artifacts and Cloud Deploy for CD.",
    resources: [
      { title: "Cloud Deploy overview", url: "https://cloud.google.com/deploy/docs/overview" },
      { title: "Cloud Deploy quickstart for Cloud Run", url: "https://cloud.google.com/deploy/docs/deploy-app-run" },
      { title: "Cloud Deploy quickstart for GKE", url: "https://cloud.google.com/deploy/docs/gke-deploy-app" },
      { title: "Cloud Deploy delivery pipelines", url: "https://cloud.google.com/deploy/docs/create-pipeline-targets" },
      { title: "Skaffold documentation", url: "https://skaffold.dev/docs/" },
      { title: "Progressive delivery on Google Cloud", url: "https://cloud.google.com/docs/ci-cd" },
    ],
  },
  {
    id: "ai-ml",
    title: "AI/ML & Troubleshooting",
    description: "Cloud Build doesn't yet have a single Gemini mode. The current pattern is AI-assisted troubleshooting, release analysis, and remediation around build logs and production signals.",
    resources: [
      { title: "Boost your CD pipeline with Generative AI", url: "https://cloud.google.com/blog/products/devops-sre/boost-your-continuous-delivery-pipeline-with-generative-ai" },
      { title: "Generative AI for root cause analysis and remediation", url: "https://cloud.google.com/blog/products/devops-sre/free-to-be-sre-how-to-use-generative-ai-for-root-cause-analysis-and-remediation" },
      { title: "Personalized Service Health with Gemini Cloud Assist", url: "https://cloud.google.com/blog/products/ai-machine-learning/how-personalized-service-health-works-with-gemini-cloud-assist" },
      { title: "Troubleshoot build failures", url: "https://cloud.google.com/build/docs/troubleshooting" },
    ],
  },
  {
    id: "migration",
    title: "Migration & Deprecations",
    description: "Key migrations: move gcr.io flows to Artifact Registry, use Cloud Build repos (2nd gen) or Developer Connect, pin builds to least-privilege service accounts.",
    resources: [
      { title: "Transition from Container Registry to Artifact Registry", url: "https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr" },
      { title: "Container Registry shutdown details", url: "https://cloud.google.com/artifact-registry/docs/transition/prepare-gcr-shutdown" },
      { title: "Cloud Build service account change", url: "https://cloud.google.com/build/docs/cloud-build-service-account-updates" },
      { title: "Cloud Source Repositories notice", url: "https://cloud.google.com/source-repositories/docs/quickstart" },
      { title: "Compute Engine container agent deprecation", url: "https://cloud.google.com/compute/docs/containers/prepare-for-container-agent-shutdown" },
    ],
  },
  {
    id: "articles",
    title: "Articles",
    resources: [
      { title: "Cloud Build release notes", url: "https://cloud.google.com/build/docs/release-notes" },
      { title: "Software Delivery Shield: secure your supply chain", url: "https://cloud.google.com/blog/products/application-development/introducing-software-delivery-shield" },
      { title: "DevSecOps and CI/CD using Google Cloud built-in services", url: "https://cloud.google.com/blog/products/application-development/devsecops-and-cicd-on-google-cloud-built-in-services" },
      { title: "Boost your CD pipeline with Generative AI", url: "https://cloud.google.com/blog/products/devops-sre/boost-your-continuous-delivery-pipeline-with-generative-ai" },
      { title: "Generative AI for root cause analysis", url: "https://cloud.google.com/blog/products/devops-sre/free-to-be-sre-how-to-use-generative-ai-for-root-cause-analysis-and-remediation" },
      { title: "Deploy applications to Cloud Run with Cloud Build", url: "https://cloud.google.com/build/docs/deploying-builds/deploy-cloud-run" },
      { title: "Best practices for building containers", url: "https://cloud.google.com/architecture/best-practices-for-building-containers" },
    ],
  },
  {
    id: "builders",
    title: "Cloud Builders",
    description: "Supported builder images from the official cloud-builders repository.",
    resources: [
      { title: "docker", url: "https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/docker" },
      { title: "gcloud", url: "https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/gcloud" },
      { title: "git", url: "https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/git" },
      { title: "go", url: "https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/go" },
      { title: "gke-deploy", url: "https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/gke-deploy" },
      { title: "kubectl", url: "https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/kubectl" },
      { title: "mvn", url: "https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/mvn" },
      { title: "npm", url: "https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/npm" },
      { title: "yarn", url: "https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/yarn" },
      { title: "curl", url: "https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/curl" },
      { title: "wget", url: "https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/wget" },
      { title: "dotnet", url: "https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/dotnet" },
      { title: "Use buildpacks instead of Dockerfiles", url: "https://cloud.google.com/docs/buildpacks/overview" },
      { title: "Create custom builders", url: "https://cloud.google.com/build/docs/configuring-builds/use-community-and-custom-builders" },
    ],
  },
  {
    id: "community-builders",
    title: "Community Cloud Builders",
    description: "Community-contributed builders from cloud-builders-community. Build and publish trusted ones into your own Artifact Registry before production use.",
    resources: [
      { title: "kaniko", url: "https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/kaniko" },
      { title: "buildah", url: "https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/buildah" },
      { title: "terraform", url: "https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/terraform" },
      { title: "terragrunt", url: "https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/terragrunt" },
      { title: "packer", url: "https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/packer" },
      { title: "pulumi", url: "https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/pulumi" },
      { title: "helm", url: "https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/helm" },
      { title: "kustomize", url: "https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/kustomize" },
      { title: "skaffold", url: "https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/skaffold" },
      { title: "firebase", url: "https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/firebase" },
      { title: "awscli", url: "https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/awscli" },
      { title: "az", url: "https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/az" },
      { title: "ansible", url: "https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/ansible" },
      { title: "shellcheck", url: "https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/shellcheck" },
    ],
  },
  {
    id: "templates",
    title: "Configuration File Templates",
    description: "Modernized cloudbuild.yaml templates for Artifact Registry, regional builds, Cloud Deploy, multi-arch images, and private pools.",
    resources: [
      { title: "Build and push to Artifact Registry", url: "https://github.com/Timtech4u/awesome-cloudbuild/blob/master/build-config-templates/build-and-push-to-artifact-registry/cloudbuild.yaml" },
      { title: "Deploy to Cloud Run", url: "https://github.com/Timtech4u/awesome-cloudbuild/blob/master/build-config-templates/deploy-to-cloud-run/cloudbuild.yaml" },
      { title: "Deploy to App Engine", url: "https://github.com/Timtech4u/awesome-cloudbuild/blob/master/build-config-templates/deploy-to-app-engine/cloudbuild.yaml" },
      { title: "Deploy to Compute Engine", url: "https://github.com/Timtech4u/awesome-cloudbuild/blob/master/build-config-templates/deploy-to-compute-engine/cloudbuild.yaml" },
      { title: "Create a Cloud Deploy release", url: "https://github.com/Timtech4u/awesome-cloudbuild/blob/master/build-config-templates/deploy-to-cloud-deploy/cloudbuild.yaml" },
      { title: "Build a multi-arch image", url: "https://github.com/Timtech4u/awesome-cloudbuild/blob/master/build-config-templates/build-multi-arch-image/cloudbuild.yaml" },
      { title: "Run builds on a private pool", url: "https://github.com/Timtech4u/awesome-cloudbuild/blob/master/build-config-templates/private-pool-build-and-push/cloudbuild.yaml" },
    ],
  },
  {
    id: "tools",
    title: "Tools",
    resources: [
      { title: "Cloud Build samples", url: "https://github.com/GoogleCloudPlatform/cloud-build-samples", description: "Reference pipelines for Docker, Cloud Run, Functions, private pools, caching, and monorepos." },
      { title: "Cloud Build notifiers", url: "https://github.com/GoogleCloudPlatform/cloud-build-notifiers", description: "Official Slack, SMTP, HTTP, BigQuery, Google Chat, and GitHub Issue notifier support." },
      { title: "Google Cloud buildpacks", url: "https://github.com/GoogleCloudPlatform/buildpacks", description: "Google-maintained buildpacks for Cloud Run, Cloud Functions, and container builds." },
      { title: "google-github-actions/auth", url: "https://github.com/google-github-actions/auth", description: "Workload Identity Federation from GitHub Actions into Google Cloud." },
      { title: "Skaffold", url: "https://skaffold.dev/", description: "Build, tag, and render support that pairs well with Cloud Build and Cloud Deploy." },
      { title: "pack CLI", url: "https://buildpacks.io/docs/for-platform-operators/how-to/integrate-ci/pack/", description: "Local CLI for buildpacks workflows." },
      { title: "SLSA verifier", url: "https://github.com/slsa-framework/slsa-verifier", description: "Verify provenance emitted by Cloud Build." },
      { title: "Terraform Google provider", url: "https://registry.terraform.io/providers/hashicorp/google/latest/docs", description: "Manage triggers, repos, worker pools, and Artifact Registry as code." },
      { title: "buildstatus", url: "https://github.com/mchmarny/buildstatus", description: "Slack notifications from Cloud Build using Cloud Run." },
      { title: "buildhub.dev", url: "https://buildhub.dev/", description: "Hosted Slack notifications for Cloud Build." },
      { title: "cloudbuild-slack", url: "https://github.com/onsails/cloudbuild-slack", description: "Slack notifier using Cloud Functions." },
      { title: "gcb-visualizer", url: "https://github.com/RyanSiu1995/gcb-visualizer", description: "Visualize Cloud Build pipelines with Graphviz." },
    ],
  },
];

export const categoryIcons: Record<string, string> = {
  "useful-links": "Link",
  "whats-new": "Sparkles",
  "quickstarts": "Rocket",
  "tutorials": "BookOpen",
  "security": "Shield",
  "repositories": "GitBranch",
  "private-pools": "Lock",
  "cloud-deploy": "Cloud",
  "ai-ml": "Brain",
  "migration": "ArrowRight",
  "articles": "FileText",
  "builders": "Hammer",
  "community-builders": "Users",
  "templates": "Code",
  "tools": "Wrench",
};
