substitutions:
  _APP_YAML: app.yaml

steps:
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  entrypoint: gcloud
  args:
  - app
  - deploy
  - ${_APP_YAML}
  - --version=${SHORT_SHA}
  - --promote
  - --quiet

options:
  logging: CLOUD_LOGGING_ONLY
