# Prefer a user-managed service account for production builds.
substitutions:
  _AR_LOCATION: us-central1
  _AR_REPOSITORY: applications
  _SERVICE: my-service
  _REGION: us-central1

steps:
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - --tag
  - ${_AR_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_SERVICE}:${SHORT_SHA}
  - .

- name: gcr.io/cloud-builders/docker
  args:
  - push
  - ${_AR_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_SERVICE}:${SHORT_SHA}

- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  entrypoint: gcloud
  args:
  - run
  - deploy
  - ${_SERVICE}
  - --image=${_AR_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_SERVICE}:${SHORT_SHA}
  - --region=${_REGION}
  - --platform=managed
  - --quiet

images:
- ${_AR_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_SERVICE}:${SHORT_SHA}

options:
  logging: CLOUD_LOGGING_ONLY
